language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "sgrillon14-github"

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew  

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
